# Generated by Django 3.2.7 on 2021-09-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20210909_0453'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='Transactions',
        ),
    ]
